version: "1.0"
services:
    webapp-service:
        container_name: "webapp-service"
        build:
            context: ./
            dockerfile: ./webapp/Dockerfile
        volumes:
          - ./webapp:/webapp
        env_file:
          - ./.env
        ports:
          - 5000:5000

        restart: always